services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    ### hot reload using watch
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    ### hot reload using volumes
    # volumes:
    #   - ./web:/app
    #   - /app/node_modules
    # environment:
    # - CHOKIDAR_USEPOLLING=true
    # - WATCHPACK_POLLING=true

    # healthcheck:
    #   test: ["CMD", "bun", "-e", "fetch('http://localhost:5000/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s